config/routes.rb
Rails.application.routes.draw do
  root to: "cars#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"



  get 'cars', to: 'cars#index' # Affiche la liste des voitures
  # get 'cars/new', to: 'cars#new' # Affiche le formulaire pour créer une nouvelle voiture
  # post 'cars', to: 'cars#create' # Crée une nouvelle voiture
  get 'cars/:id', to: 'cars#show', as: 'car' # Affiche les détails d'une voiture spécifique
  get 'cars/:id/edit', to: 'cars#edit', as: 'edit_car' # Affiche le formulaire pour modifier une voiture
  patch 'cars/:id', to: 'cars#update' # Met à jour une voiture spécifique
  delete 'cars/:id', to: 'cars#destroy' # Supprime une voiture spécifique

  get 'user/id', to:"user#show", as: 'user'

  resources :bookings

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_one :user
  has_one :car

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :price, presence: true
  validates :status, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user

  validates :matriculation, presence: true, uniqueness: true
  validates :brand, presence: true
  validates :model, presence: true
  validates :year, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings

  validates :name, uniqueness: true, presence: true
  validates :adress, presence: true
  validates :email, presence: true
  validates :profile_pic, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def show
    get_booking
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to @booking, notice: "La réservation a été créée avec succès."
    else
      render :new
    end
  end



  def update
    @booking.update(booking_params)
    end

    def destroy
      @booking = Booking.find(params[:id]).destroy
    end


  private

  def get_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # before_action :set_car, only: [:show, :index]


  def index
    @cars = Car.all
  end

  # GET /car/:id
  def show
    set_car
  end

  def edit
  end

  def update
    @car.update(car_params)
    end

    def destroy
      @car = Car.find(params[:id]).destroy
    end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:car_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    set_user
  end

  # # GET /users/new
  # def new
  # #   @user = User.new
  # end

  # # GET /users/1/edit
  # def edit
  # end

  # # POST /users
  # # POST /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /users/1
  # # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<!--
<%= form_with url: '/bookings', method: :post do |form| %>
  <%= form.label :selected_date, 'Select Date:' %>
  <%= form.date_field :selected_date, id: 'selected_date_field' %>
  <%= form.submit 'Submit' %>
<% end %>

<% if params[:bookings] && params[:bookings][:selected_date] %>
  <p>Selected Date: <%= params[:bookings][:selected_date] %></p>
<% end %>



-->


<!-- app/views/bookings/new.html.erb

<h1>Réserver une voiture</h1>

<%= form_with(model: @booking, local: true) do |form| %>


  <div class="field">
    <%= form.label :start_date, "Date de début" %>
    <%= form.date_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date, "Date de fin" %>
    <%= form.date_field :end_date %>
  </div>

  <div class="field">
    <%= form.label :user_id, "ID de l'utilisateur" %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :car_id, "ID de la voiture" %>
    <%= form.text_field :car_id %>
  </div>

  <div class="actions">
    <%= form.submit "Réserver la voiture" %>
  </div>
<% end %>

<%= link_to "Retour à la liste des voitures", cars_path %> -->


<!-- app/views/bookings/index.html.erb -->
<h1>Liste des réservations</h1>

<% @bookings.each do |booking| %>
  <div>
    <p>Date de réservation : <%= booking.created_at.strftime("%d/%m/%Y %H:%M") %></p>
    <!-- Autres détails de la réservation ici -->
    <%= link_to "Voir le récap", booking_path(booking), class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Retour à la liste des voitures", cars_path %>

app/views/bookings/new.html.erb
<!-- app/views/bookings/new.html.erb -->
<h1>Nouvelle réservation</h1>

<%= form_with url: bookings_path, method: :post do |form| %>
  <%= csrf_meta_tags %>

<%= form.label :start_date, 'Date de début:' %>
  <%= form.date_field :start_date %>




    <%= form.submit "Submit" %>
  <% end %>

<p>Selected Date: <%= params[:start_date] %></p>




<% if @booking %>
  <div>
    <h2>Récapitulatif de votre réservation :</h2>
    <p>Date de fin : <%= @booking.end_date %></p>
  </div>
<% end %>

app/views/cars/index.html.erb
<!-- app/views/cars/index.html.erb -->

<h1>Liste des voitures</h1>

<table>

  <% @cars.each do |car| %>
    <div class="card" style="width: 18rem;">
        <%= image_tag url_for(car.photo) %>
      <div class="card-body">
        <h5 class="card-title"><%= car.brand %> <%= car.model %></h5>
        <p class="card-text"><%= car.year %></p>
        <p class="card-text"><%= car.matriculation %></p>
        <%= link_to 'Voir', car_path(car), class: "btn btn-primary" %>

      </div>
    </div>
  <% end %>


</table>



<%# <%= link_to "Ajouter une voiture", new_car_path, class: "btn btn-success" %>

app/views/cars/show.html.erb
<!-- app/views/cars/show.html.erb -->

<h1>Détails de la voiture <%= @car.brand %> <%= @car.model %></h1>

<dl>
  <dt>Marque :</dt>
  <dd><%= @car.brand %></dd>

  <dt>Modèle :</dt>
  <dd><%= @car.model %></dd>

  <dt>Année :</dt>
  <dd><%= @car.year %></dd>

  <dt> Immatriculation : </dt>
  <dd><%= @car.matriculation %></dd>
</dl>
<%= link_to "Book", new_booking_path, class: "btn btn-secondary" %>
<%= link_to "Retour", cars_path, class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Entrainement</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->

<h1>Profil de <%= @user.username %></h1>

<dl>
  <dt>Nom :</dt>
  <dd><%= @user.last_name %></dd>

  <dt>Prénom :</dt>
  <dd><%= @user.first_name %></dd>

  <!-- Ajoutez d'autres informations sur l'utilisateur selon vos besoins -->
</dl>

<%= link_to "Modifier mon profil", edit_user_path(@user), class: "btn btn-primary" %>
<%= link_to "Retour", users_path, class: "btn btn-secondary" %>